### PR TITLE
Fix: Separate CPU and GPU LLVM optimization pipelines before GPU lowering

### LINKED ISSUE #792: GPU lowering inherits CPU-vectorized `llvm.exp.v8f32` and fails during NVPTX Codegen
## Summary
A GPU kernel containing an elementwise `np.exp(...)` expression can fail during NVPTX codegen.

The failure occurs because a CPU-vectorized LLVM intrinsic such as `@llvm.exp.v8f32` is introduced into the GPU module before GPU lowering. That LLVM vector intrinsic is not handled by the current NVPTX remapping path, and codegen later fails with:

```shell
$ codon build -release 02_gpu_exp_on_expr.codon 
error: no libcall available for fexp
```

## MRE
```python
import gpu
import numpy as np

@gpu.kernel
def exp_kernel_naver_02(x, out):
    out[:] = np.exp(x - 1.0f32)

def main():
    x = np.array([0.0, 1.0, -1.0, 2.0], dtype=np.float32)
    out = np.empty(x.shape, dtype=np.float32)
    exp_kernel_naver_02(x, out, grid=1, block=1)
    print(out)

if __name__ == "__main__":
    main()

```
## IR Observation after `remapFunctions`

Most math library call symbols, especially `exp` supposed to be remapped to NVPTX/libdevice symbols:
```python
...
  %y = call float @llvm.exp.f32(float %x), !dbg !38796
...
# After remapping phase, intrinsic turns into below
...
  %y.i.i.i.i.i.i.i112.i.i.i.1 = tail call float @__nv_expf(float %tmp.i.i.i.i.i111.i.i.i.1)
...
```

But that's for only scalar intrinsic calls, not for vector case:
```python
...
  %25 = tail call <8 x float> @llvm.exp.v8f32(<8 x float> %24)
...
# Even after remapping phase, SIMT intrinsic does not turn into NVPTX symbol.
```

## Why it fails
The reported `fexp` is not a source-level symbol and not an `LLVM IR` function name either. It appears to correspond to LLVM's internal `SelectionDAG opcode` for exponential (ISD::FEXP).

So, lowering is likely to be:
- `@llvm.exp.v8f32` still remains as it is not mapped.
- LLVM Back-End lowers it into internal `FEXP DAG node`
- LLVM attempts libcall of `FEXP`
- But NVPTX does not provide libcall path, and actually also Codon does not seem to want it (it must remapped before LLVM pass run through `remappedFunctions`.).
- So Codegen fails.

## Root Cause
Current compile pipeline run `native CPU LLVM optimization` before GPU module separation:
```C++
void optimize(llvm::Module *module, bool debug, bool jit, PluginManager *plugins) {
  verify(module);
  {
    TIME("llvm/opt1");
    runLLVMOptimizationPasses(module, debug, jit, plugins);
  }
  if (!debug) {
    TIME("llvm/opt2");
    runLLVMOptimizationPasses(module, debug, jit, plugins);
  }
  {
    TIME("llvm/gpu");
    applyGPUTransformations(module);
  }
  verify(module);
}
```
As GPU module extraction/cloning/patching happens after `native CPU Optimization`, GPU module can inherit CPU-oriented vectorization intrinsics.

### PR DESCRIPTION
**Pull request by BI71317**
fixes #792 

## What this PR Fixes
This PR changes the pipeline structure so that CPU and GPU modules are separated before their respective optimization flows are applied.

## 2-pass Optimization
Like CPU Module, also GPU module introduced 2-pass Optimzation.

But Not only for performance,

### When Only 1-pass Optimzation is occured,
```

.version 4.2
.target sm_30
.address_size 64

	// .globl	std_numpy_indexing__getset_0_0_std_numpy_ndarray_ndarray_0_float32_1__Tuple_std_internal_types_slice_Slice_0_int_int_int___std_numpy_ndarray_ndarray_0_float32_1__float32__3860
.extern .func  (.param .b64 func_retval0) malloc
(
	.param .b64 malloc_param_0
)
;
.visible .func std_numpy_util_multirange_0_0_Tuple_int___3272_resume
(
	.param .b64 std_numpy_util_multirange_0_0_Tuple_int___3272_resume_param_0
)
;
.extern .global .align 1 .b8 _str_209[2];
.extern .global .align 1 .b8 _str_210[2];
.extern .global .align 1 .b8 _str_211[2];
.extern .global .align 1 .b8 _str_212[2];
.extern .global .align 1 .b8 _str_223[2];
.extern .global .align 1 .b8 _str_224[2];
.extern .global .align 1 .b8 _str_225[2];
.extern .global .align 1 .b8 _str_226[2];
.extern .global .align 1 .b8 _str_272[2];
.extern .global .align 1 .b8 _str_273[2];
.extern .global .align 1 .b8 _str_274[2];
.extern .global .align 1 .b8 _str_275[2];
.extern .global .align 1 .b8 _str_276[2];
.extern .global .align 1 .b8 _str_277[2];
.extern .global .align 1 .b8 _str_278[2];
.extern .global .align 1 .b8 _str_279[2];
.extern .global .align 1 .b8 _str_280[2];
.extern .global .align 1 .b8 _str_313[2];
.extern .global .align 1 .b8 _str_318[2];
...

```

Un-inlined GV are retained, these seems to occur invalid PTX.

### 2-pass

```
.version 4.2
.target sm_30
.address_size 64

	// .globl	exp_kernel_naver_02_0_0_std_numpy_ndarray_ndarray_0_float32_1__std_numpy_ndarray_ndarray_0_float32_1__
.extern .func  (.param .b64 func_retval0) malloc
(
	.param .b64 malloc_param_0
)
;
...
```

Seems 2-pass opt inlines GV, And this case works correctly.

## ApplyGPUTransformation
`ApplyGPUTransformation` does lots of jobs. 

It clones module, separate CPU and GPU module, run NVPTX passes, cleanup CPU module, and Patches.

In only one Function, it contains these jobs, so to optimize each module, dividing logic of this function was inevitable I think.

### CODE REVIEW

**Comment by arshajii** [comment]
Thanks for the PR, @BI71317! Quick question as I'm reviewing: does this also address https://github.com/exaloop/codon/issues/781?

**Comment by BI71317** [comment]
Hey, @arshajii!

Before pushing this PR, I also thought this issue might be related with GV un-init problem.

After implement done, I checked ptx of #781 MRE, and this is what it looks like:

```
//
// Generated by LLVM NVPTX Back-End
//

.version 4.2
.target sm_30
.address_size 64

	// .globl	kernel_0_0_std_internal_types_array_List_0_float__
.visible .global .align 4 .f32 _pi32_0;

.visible .entry kernel_0_0_std_internal_types_array_List_0_float__(
	.param .u64 .ptr .align 1 kernel_0_0_std_internal_types_array_List_0_float___param_0
)
{
	.reg .b32 	%r<2>;
	.reg .f32 	%f<2>;
	.reg .b64 	%rd<6>;
	.reg .f64 	%fd<2>;

	ld.param.u64 	%rd1, [kernel_0_0_std_internal_types_array_List_0_float___param_0];
	cvta.to.global.u64 	%rd2, %rd1;
	mov.u32 	%r1, %tid.x;
	ld.global.f32 	%f1, [_pi32_0];
	cvt.f64.f32 	%fd1, %f1;
	ld.global.u64 	%rd3, [%rd2+16];
	mul.wide.u32 	%rd4, %r1, 8;
	add.s64 	%rd5, %rd3, %rd4;
	st.f64 	[%rd5], %fd1;
	ret;

}

```

## result

```
$ ./pi32_gpu_f32
out:  0
math.pi32:  3.14159
AssertionError: Assert failed (/home/swchoi/src/test_code/codon_math_matrix/generated/cases/nvptx/pi32_gpu_f32.codon:17)

Raised from: 
/home/swchoi/src/test_code/codon_math_matrix/generated/cases/nvptx/pi32_gpu_f32.codon:17:1
Aborted (core dumped)
```

Result seems to say that it still un-inits GV.

File: codon/cir/llvm/gpu.cpp [hunk 1]
```diff
@@ -945,16 +945,19 @@ void patchPTXVar(llvm::Module *M, llvm::GlobalValue *ptxVar,
...
   clone->setDataLayout(GPU_DL);
   if (isFastMathOn()) {
     clone->addModuleFlag(llvm::Module::ModFlagBehavior::Override, "nvvm-reflect-ftz",
                          1);
   }
+  return clone;
+}
 
+void applyGPUTransformations(llvm::Module *M, std::unique_ptr<llvm::Module> clone, const std::string &ptxFilename) {
+    llvm::LLVMContext &context = M->getContext();
```
Comment (arshajii) [inline codon/cir/llvm/gpu.cpp]: Please format these changes with `clang-format`, i.e. `clang-format -i gpu.cpp ...`

File: codon/cir/llvm/gpu.h [hunk 2]
```diff
@@ -15,7 +15,9 @@ namespace ir {
 /// annotation)
 /// @param ptxFilename Filename for output PTX code; empty to use filename based on
 /// module
-void applyGPUTransformations(llvm::Module *module, const std::string &ptxFilename = "");
+
+std::unique_ptr<llvm::Module> prepareGPUmodule(llvm::Module *module);
```
Comment (arshajii) [inline codon/cir/llvm/gpu.h]: Comments above refer to the old `applyGPUTransformations` -- can we please update this comment, move it to be above the `applyGPUTransformations` declaration, and add a similar one for the new `prepareGPUmodule()` since it is technically in the public API.

File: codon/cir/llvm/optimize.cpp [hunk 3]
```diff
@@ -1074,17 +1084,34 @@ void verify(llvm::Module *module) {
...
   verify(module);
+  std::unique_ptr<llvm::Module> GPUmodule;
+  {
+    TIME("preparing/gpu");
+    GPUmodule = prepareGPUmodule(module);
+  }
   {
     TIME("llvm/opt1");
-    runLLVMOptimizationPasses(module, debug, jit, plugins);
+    runLLVMOptimizationPasses(module, debug, jit, plugins, true, true);
```
Comment (arshajii) [inline codon/cir/llvm/optimize.cpp]: Please add argument names to the literal `true` arguments (i.e. `/*includeNative=*/true` etc.) to be consistent with below.

**Review by arshajii — CHANGES_REQUESTED** [review]

**Comment by arshajii** [comment]
Thanks for the info! Just left a few minor comments, but otherwise this looks good. Can you please also confirm that the test `test/transform/kernels.codon` runs & succeeds with these changes? You should be able to just run it directly with `codon run -release`.

File: codon/cir/llvm/gpu.h (hunk 2 above)
Comment (BI71317) [reply codon/cir/llvm/gpu.h]: For sure. As preparing GPU module Phase is separated from applyGPUTransformations, comment for clone argument also added in applyGPUTransformations.

File: codon/cir/llvm/gpu.cpp (hunk 1 above)
Comment (BI71317) [reply codon/cir/llvm/gpu.cpp]: For sure. Next time, I won't forget it.

**Comment by BI71317** [comment]
> Can you please also confirm that the test `test/transform/kernels.codon` runs & succeeds with these changes?

And yeah. It seems to run without build failure or runtime error.

image

**Comment by arshajii** [comment]
Thanks! Merging now...
